default: &default
      adapter: postgresql
      encoding: unicode
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
      username: <%= ENV['USERNAME'] %>
      password: <%= ENV['PASSWORD'] %>
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: basic_db

test:
  <<: *default
  database: app_test

production:
  <<: *default
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  database: basic-borders_production