source 'https://rubygems.org'

ruby '2.5.3'

gem 'rails', '5.2.3'  # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

# gem 'actionpack'

gem 'coffee-script'
gem 'therubyracer'
gem 'sassc-rails'

gem 'less-rails', '~> 3.0.0'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'  # Use Uglifier as compressor for JavaScript assets

gem 'jquery-rails' # Use jquery as the JavaScript library
gem 'jbuilder', '~> 2.0' # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'sdoc', '~> 0.4.0', group: :doc # bundle exec rake doc:rails generates the API under doc/api.

gem 'bcrypt', '~> 3.1.7'
gem 'devise', '> 4.2.0'

gem 'turbolinks', '~> 5'

gem 'will_paginate', '~> 3.1', '>= 3.1.5'
gem 'bootstrap-will_paginate', '~> 0.0.10'
gem 'rails_admin'
gem 'active_hash_relation', '~> 1.4.1'
gem 'active_model_serializers' #, github: 'rails-api/active_model_serializers'
gem 'simple_form'
gem 'cocoon'

gem 'faker'



group :development, :test do
  gem 'byebug'  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'pry'
  gem 'pry-byebug'
  gem 'sqlite3' # Use sqlite3 as the database for Active Record
  gem 'haml'
  gem 'haml-rails'
  gem 'capybara'
  
  gem 'selenium-webdriver'
  gem 'chromedriver-helper'
  # gem 'webdriver'
  gem 'nokogiri' # required for minitest-have_tag
  gem "minitest", "5.10.1"
  # gem 'minitest-rails'
  gem 'minitest-reporters'
  gem 'minitest-color'
  gem 'guard', '~>2.14'
  gem 'guard-minitest'
  gem 'rails-controller-testing'
  gem 'hihi'
 # gem 'minitest-have_tag' #html checking for mini test...include/require in spechelper too
  gem 'factory_bot'
  gem 'loofah'
end

group :test do

end

group :production do
  gem 'pg', '0.18.4'
  gem 'puma'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring'
end

